services:
  flet:
    extends:
      file: docker-compose-python_template.yml
      service: python
    build:
      context: ./flask
    container_name: flask-app
    restart: always
    ports:
      - "${PORT_FLASK}:${PORT_FLASK}"
    volumes:
      - ./flask/log:/usr/src/app/log
      - ./flask/src:/usr/src/app/src:volume-nocopy
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app/src
        uvicorn app:app --host 0.0.0.0 --port ${PORT_FLASK} --workers 4
